<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9103" started-at="2018-10-09T09:34:20Z" finished-at="2018-10-09T09:34:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9103" started-at="2018-10-09T09:34:20Z" finished-at="2018-10-09T09:34:29Z">
      <class name="confirmation_testsuit.Confirm_Customer_Validate_Response">
        <test-method status="FAIL" signature="test1()[pri:0, instance:confirmation_testsuit.Confirm_Customer_Validate_Response@131774fe]" name="test1" duration-ms="9068" started-at="2018-10-09T09:34:20Z" finished-at="2018-10-09T09:34:29Z">
          <exception class="java.lang.ClassCastException">
            <message>
              <![CDATA[java.util.HashMap cannot be cast to java.util.List]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.List
at io.restassured.path.json.JsonPath.getList(JsonPath.java:374)
at confirmation_testsuit.Confirm_Customer_Validate_Response.test1(Confirm_Customer_Validate_Response.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ClassCastException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- confirmation_testsuit.Confirm_Customer_Validate_Response -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
